# .github/workflows/ci.yml

name: Node.js CI

on:
  push:
    branches: [ "main", "master" ] # Adjust branches as needed
  pull_request:
    branches: [ "main", "master" ] # Adjust branches as needed

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify Node versions to test against
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci # Use npm ci for cleaner installs in CI
      
    - name: Run unit tests
      run: npm test -- --coverage # Use npm test script which should call jest 